kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-airflow-dags
  namespace: airflow
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  nfs:
    path: /
    server: fs-6e8244a4.efs.eu-west-1.amazonaws.com
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-airflow-logs
  namespace: airflow
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs

  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  nfs:
    path: /
    server: fs-6e8244a4.efs.eu-west-1.amazonaws.com
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-airflow-dags
  namespace: airflow
#  annotations: volume.beta.kubernetes.io/storage-class: "aws-efs"	  	#added
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 8Gi
  volumeName: nfs-airflow-dags
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-airflow-logs
  namespace: airflow
#  annotations:	volume.beta.kubernetes.io/storage-class: "aws-efs"		#added
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 8Gi
  volumeName: nfs-airflow-logs
---
